/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import static com.app.GameJFrame.Code1;
import static com.app.GameJFrame.Code2;
import static com.app.GameJFrame.Code3;
import static com.app.GameJFrame.Code4;
import static com.app.GameJFrame.count;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Mes dossiers
 */
public class JMFrame extends javax.swing.JFrame {
 ImageIcon filled = new ImageIcon (getClass().getResource("/Images/circle_filled.png"));
     ImageIcon unfilled = new ImageIcon (getClass().getResource("/Images/circle_unfilled.png"));
    int xMouse;
    int yMouse;
    boolean ex=false;
   
     /**
     * Creates new form MessageJfram
     */
    public JMFrame() {
        initComponents();
        this.setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        DraggFrame = new javax.swing.JLabel();
        jouerButon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(370, 132));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitSimple.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(340, 0, 30, 30);

        DraggFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        DraggFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggFrameMouseDragged(evt);
            }
        });
        DraggFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggFrameMousePressed(evt);
            }
        });
        getContentPane().add(DraggFrame);
        DraggFrame.setBounds(0, 0, 370, 30);

        jouerButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/okLeaved.png"))); // NOI18N
        jouerButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jouerButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jouerButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jouerButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jouerButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jouerButonMouseReleased(evt);
            }
        });
        getContentPane().add(jouerButon);
        jouerButon.setBounds(170, 90, 50, 15);

        background.setForeground(new java.awt.Color(255, 0, 0));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/JMessageFrame.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 370, 132);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        // TODO add your handling code here:
        
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
         Code1.setIcon(unfilled); 
           Code2.setIcon(unfilled); 
                 Code3.setIcon(unfilled);
                 Code4.setIcon(unfilled);
                 count = 0 ;
        this.dispose();
   
    }//GEN-LAST:event_exitMouseReleased

    private void DraggFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggFrameMouseDragged
      int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_DraggFrameMouseDragged

    private void DraggFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggFrameMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_DraggFrameMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
       ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/exitnt.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
   ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseExited

    private void jouerButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseEntered
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/okEntred.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseEntered

    private void jouerButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseExited
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/okLeaved.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseExited

    private void jouerButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMousePressed
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/okCliked.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMousePressed

    private void jouerButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseReleased
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/okLeaved.png"));
        jouerButon.setIcon(II);
        Code1.setIcon(unfilled); 
           Code2.setIcon(unfilled); 
                 Code3.setIcon(unfilled);
                 Code4.setIcon(unfilled);
                 count = 0 ;
                 this.dispose();
    }//GEN-LAST:event_jouerButonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DraggFrame;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jouerButon;
    // End of variables declaration//GEN-END:variables
}
