/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import javax.swing.ImageIcon;
import java.io.*;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.*;
import sun.audio.*;


/**
 *
 * @author Mes dossiers
 */
public class MenuJFrame extends javax.swing.JFrame {
   int xMouse;
   int yMouse;
    /**
     * Creates new form ScoreJFrame
     */
    public MenuJFrame() {
        initComponents();
        this.setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispose = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        move = new javax.swing.JLabel();
        jouerButon = new javax.swing.JLabel();
        regleButon = new javax.swing.JLabel();
        quiterButon = new javax.swing.JLabel();
        BarBackground = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        dispose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/defaultsimple.png"))); // NOI18N
        dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                disposeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                disposeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                disposeMouseReleased(evt);
            }
        });
        getContentPane().add(dispose);
        dispose.setBounds(686, 10, 30, 30);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitSimple.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(723, 10, 30, 30);

        move.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move);
        move.setBounds(0, 0, 760, 50);

        jouerButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jouerLeaved.png"))); // NOI18N
        jouerButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jouerButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jouerButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jouerButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jouerButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jouerButonMouseReleased(evt);
            }
        });
        getContentPane().add(jouerButon);
        jouerButon.setBounds(290, 110, 230, 70);

        regleButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/regleLeaved.png"))); // NOI18N
        regleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regleButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regleButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regleButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                regleButonMouseReleased(evt);
            }
        });
        getContentPane().add(regleButon);
        regleButon.setBounds(290, 200, 230, 70);

        quiterButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quiterExited.png"))); // NOI18N
        quiterButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quiterButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quiterButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quiterButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quiterButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                quiterButonMouseReleased(evt);
            }
        });
        getContentPane().add(quiterButon);
        quiterButon.setBounds(290, 290, 230, 70);

        BarBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarBackground.png"))); // NOI18N
        getContentPane().add(BarBackground);
        BarBackground.setBounds(0, -50, 840, 430);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 760, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
    System.exit(0);
    }//GEN-LAST:event_exitMouseReleased

    private void disposeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseReleased
      this.setExtendedState(GameJFrame.ICONIFIED);
                                          
    }//GEN-LAST:event_disposeMouseReleased

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
     int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);  
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
    xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
     
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
     ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/exitnt.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseEntered

    private void disposeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseEntered
    ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultIN.png"));
       dispose.setIcon(exitIcon);
    }//GEN-LAST:event_disposeMouseEntered

    private void disposeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseExited
         ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultsimple.png"));
       dispose.setIcon(exitIcon);
    }//GEN-LAST:event_disposeMouseExited

    private void jouerButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseExited
       ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerLeaved.png"));
       jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseExited

    private void jouerButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseEntered
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerEntred.png"));
       jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseEntered

    private void jouerButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMousePressed
    ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerCliked.png"));
       jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMousePressed

    private void jouerButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseReleased
       this.dispose();
     new GameJFrame ().setVisible (true);
   
    }//GEN-LAST:event_jouerButonMouseReleased

    private void regleButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regleButonMouseEntered
       
         ImageIcon II = new ImageIcon (getClass().getResource("/Images/regleExited.png"));
       regleButon.setIcon(II);
    }//GEN-LAST:event_regleButonMouseEntered

    private void regleButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regleButonMouseExited
       ImageIcon II = new ImageIcon (getClass().getResource("/Images/regleLeaved.png"));
       regleButon.setIcon(II);
    }//GEN-LAST:event_regleButonMouseExited

    private void regleButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regleButonMousePressed
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/regleCliked.png"));
       regleButon.setIcon(II);
    }//GEN-LAST:event_regleButonMousePressed

    private void regleButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regleButonMouseReleased
        this.dispose();
        RegleJframe RJF= new RegleJframe();
        RJF.setVisible (true);
    }//GEN-LAST:event_regleButonMouseReleased

    private void quiterButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quiterButonMouseExited
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/quiterExited.png"));
       quiterButon.setIcon(II);
    }//GEN-LAST:event_quiterButonMouseExited

    private void quiterButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quiterButonMousePressed
       ImageIcon II = new ImageIcon (getClass().getResource("/Images/quiterPressed.png"));
       quiterButon.setIcon(II);
    }//GEN-LAST:event_quiterButonMousePressed

    private void quiterButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quiterButonMouseEntered
           ImageIcon II = new ImageIcon (getClass().getResource("/Images/quiterEntred.png"));
       quiterButon.setIcon(II);
                                        
    }//GEN-LAST:event_quiterButonMouseEntered

    private void quiterButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quiterButonMouseReleased
    System.exit(0);
    }//GEN-LAST:event_quiterButonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BarBackground;
    private javax.swing.JLabel dispose;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jouerButon;
    private javax.swing.JLabel move;
    private javax.swing.JLabel quiterButon;
    private javax.swing.JLabel regleButon;
    // End of variables declaration//GEN-END:variables
}
