/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import static com.app.GameJFrame.Code1;
import static com.app.GameJFrame.Code2;
import static com.app.GameJFrame.Code3;
import static com.app.GameJFrame.Code4;
import static com.app.GameJFrame.count;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Mes dossiers
 */
public class MessageJfram extends javax.swing.JFrame {
 ImageIcon filled = new ImageIcon (getClass().getResource("/Images/circle_filled.png"));
     ImageIcon unfilled = new ImageIcon (getClass().getResource("/Images/circle_unfilled.png"));
    int xMouse;
    int yMouse;
    boolean ex=false;
    public JLabel getT(){
        return T;
    }
     public JLabel getV(){
        return V;
       
    }
      
     /**
     * Creates new form MessageJfram
     */
    public MessageJfram() {
        initComponents();
        this.setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T = new javax.swing.JLabel();
        V = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        DraggFrame = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(279, 135));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        T.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        T.setForeground(new java.awt.Color(255, 255, 255));
        T.setText("3");
        getContentPane().add(T);
        T.setBounds(133, 84, 10, 22);

        V.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        V.setForeground(new java.awt.Color(255, 255, 255));
        V.setText("1");
        getContentPane().add(V);
        V.setBounds(180, 84, 10, 22);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitSimple.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(250, 0, 30, 30);

        DraggFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        DraggFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DraggFrameMouseDragged(evt);
            }
        });
        DraggFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DraggFrameMousePressed(evt);
            }
        });
        getContentPane().add(DraggFrame);
        DraggFrame.setBounds(0, 0, 280, 30);

        background.setForeground(new java.awt.Color(255, 0, 0));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panBacksimple.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 279, 135);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        // TODO add your handling code here:
         ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
        Code1.setIcon(unfilled); 
           Code2.setIcon(unfilled); 
                 Code3.setIcon(unfilled);
                 Code4.setIcon(unfilled);
                 count = 0 ;
        this.dispose();
   
    }//GEN-LAST:event_exitMouseReleased

    private void DraggFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggFrameMouseDragged
      int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_DraggFrameMouseDragged

    private void DraggFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DraggFrameMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_DraggFrameMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
  ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/exitnt.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
     ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageJfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DraggFrame;
    private javax.swing.JLabel T;
    private javax.swing.JLabel V;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    // End of variables declaration//GEN-END:variables
}
