/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

/**
 *
 * @author Mes dossiers
 */
public class RegleJframe extends javax.swing.JFrame {
  int xMouse;
  int yMouse;
    /**
     * Creates new form RegleJframe
     */
  AnimationClass AC = new AnimationClass();
    public RegleJframe() {
        initComponents();
        this.setLocationRelativeTo (null);
        SlideShow ();
    }
    public void SlideShow ()
    {
        new Thread ()
        {
            int count;
            @Override
            public void run ()
            {
              try {
                while (true){
              switch (count) {
                case 0:
                    ImageIcon II = new ImageIcon(getClass().getResource("/Images/Background1.png"));
                    Background1.setIcon  (II);
                    Thread.sleep(5100);
                    AC.jLabelXLeft(0, -760, 10, 2, Background1);
                    AC.jLabelXLeft(760, 0, 10, 2, Background2);
                     count=1;
                     
                    break;
                case 1:
                    ImageIcon II1= new ImageIcon(getClass().getResource("/Images/Background2.png"));
                    Background2.setIcon  (II1);
                    Thread.sleep(7100);
                    AC.jLabelXRight(-760, 0, 10, 2,Background1);
                    AC.jLabelXRight(0, 760, 10, 2, Background2);
                     count=2;
                    break;
                   case 2:
                       ImageIcon II2 = new ImageIcon(getClass().getResource("/Images/Background3.png"));
                    Background1.setIcon  (II2);
                    Thread.sleep(10100);
                    AC.jLabelXLeft(0, -760, 10, 2, Background1);
                    AC.jLabelXLeft(760, 0, 10, 2, Background2);
                     count=3;
                    break;
                case 3:
                    ImageIcon II3 = new ImageIcon(getClass().getResource("/Images/Background4.png"));
                    Background2.setIcon  (II3);
                    Thread.sleep(10100);
                    AC.jLabelXRight(-760, 0, 10, 2, Background1);
                    AC.jLabelXRight(0, 760, 10, 2, Background2);
                     count=0;
                    break;
                
                
                
              }
            
             }
        
            }catch (Exception e)
          {
          }
              }
        
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        Defaut = new javax.swing.JLabel();
        move = new javax.swing.JLabel();
        jouerButon = new javax.swing.JLabel();
        BarBackground = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 460));
        setUndecorated(true);
        getContentPane().setLayout(null);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitSimple.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(723, 10, 30, 30);

        Defaut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/defaultsimple.png"))); // NOI18N
        Defaut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Defaut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DefautMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DefautMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DefautMouseReleased(evt);
            }
        });
        getContentPane().add(Defaut);
        Defaut.setBounds(686, 10, 30, 30);

        move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarBackground.png"))); // NOI18N
        move.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move);
        move.setBounds(0, 0, 760, 70);

        jouerButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jouerLeaved.png"))); // NOI18N
        jouerButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jouerButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jouerButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jouerButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jouerButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jouerButonMouseReleased(evt);
            }
        });
        getContentPane().add(jouerButon);
        jouerButon.setBounds(520, 360, 230, 70);

        BarBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarBackground.png"))); // NOI18N
        getContentPane().add(BarBackground);
        BarBackground.setBounds(0, -50, 860, 430);

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background2.png"))); // NOI18N
        Background2.setText("jLabel1");
        Background2.setMaximumSize(new java.awt.Dimension(760, 460));
        Background2.setMinimumSize(new java.awt.Dimension(760, 460));
        Background2.setPreferredSize(new java.awt.Dimension(760, 460));
        getContentPane().add(Background2);
        Background2.setBounds(760, 0, 760, 460);

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background1.png"))); // NOI18N
        getContentPane().add(Background1);
        Background1.setBounds(0, 0, 760, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 760, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DefautMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefautMouseReleased
         this.setExtendedState(GameJFrame.ICONIFIED);
    }//GEN-LAST:event_DefautMouseReleased

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        System.exit(0);
    }//GEN-LAST:event_exitMouseReleased

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
         int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
         xMouse = evt.getX();
        yMouse = evt.getY(); 
      
    }//GEN-LAST:event_moveMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
      ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/exitnt.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited

        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseExited

    private void DefautMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefautMouseExited
      ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultsimple.png"));
        Defaut.setIcon(exitIcon);
    }//GEN-LAST:event_DefautMouseExited

    private void DefautMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefautMouseEntered
      ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultIN.png"));
        Defaut.setIcon(exitIcon);
    }//GEN-LAST:event_DefautMouseEntered

    private void jouerButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseEntered
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerEntred.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseEntered

    private void jouerButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseExited
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerLeaved.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseExited

    private void jouerButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMousePressed
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/jouerCliked.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMousePressed

    private void jouerButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseReleased
        this.dispose();
        GameJFrame GJF=new GameJFrame ();
        GJF.setVisible (true);
    }//GEN-LAST:event_jouerButonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegleJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegleJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel BarBackground;
    private javax.swing.JLabel Defaut;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jouerButon;
    private javax.swing.JLabel move;
    // End of variables declaration//GEN-END:variables
}
