/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Mes dossiers
 */
public class ScoreJFrame extends javax.swing.JFrame {
   int xMouse;
   int yMouse;
    public JLabel getIcon1 (){
       return Icon1;
   }  
   public JLabel getIcon2 (){
       return Icon2;
   } 
   public JLabel getIcon (){
       return Icon;
   } 
   public JLabel getBack() {
       return  Background2;  
   }
   public JLabel getM() {
       return m;  
   }
      public JLabel getC() {
       return c;  
   }
      public JLabel getNbr() {
       return nbr;  
   }
     
      
      public JLabel getD() {
       return d;  
   }
      public JLabel getU() {
       return u;  
   }

    /**
     * Creates new form ScoreJFrame
     */
    public ScoreJFrame() {
        initComponents();
        this.setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispose = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        nbr = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        move = new javax.swing.JLabel();
        Icon2 = new javax.swing.JLabel();
        Icon1 = new javax.swing.JLabel();
        jouerButon = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        BarBackground = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        dispose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/defaultsimple.png"))); // NOI18N
        dispose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dispose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                disposeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                disposeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                disposeMouseReleased(evt);
            }
        });
        getContentPane().add(dispose);
        dispose.setBounds(686, 10, 30, 30);

        m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Number-1-icon.png"))); // NOI18N
        getContentPane().add(m);
        m.setBounds(320, 255, 32, 32);

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        getContentPane().add(c);
        c.setBounds(360, 255, 32, 32);

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        getContentPane().add(d);
        d.setBounds(400, 255, 32, 32);

        u.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        getContentPane().add(u);
        u.setBounds(440, 255, 32, 32);

        nbr.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nbr.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nbr);
        nbr.setBounds(310, 358, 30, 30);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitSimple.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(723, 10, 30, 30);

        move.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move);
        move.setBounds(0, 0, 760, 50);
        getContentPane().add(Icon2);
        Icon2.setBounds(230, 160, 50, 50);
        getContentPane().add(Icon1);
        Icon1.setBounds(510, 160, 70, 50);

        jouerButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rejouerLeaved.png"))); // NOI18N
        jouerButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jouerButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jouerButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jouerButonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jouerButonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jouerButonMouseReleased(evt);
            }
        });
        getContentPane().add(jouerButon);
        jouerButon.setBounds(490, 340, 230, 70);

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/youWin.png"))); // NOI18N
        Background2.setToolTipText("");
        getContentPane().add(Background2);
        Background2.setBounds(0, 0, 760, 460);

        BarBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarBackground.png"))); // NOI18N
        getContentPane().add(BarBackground);
        BarBackground.setBounds(0, -50, 840, 430);
        getContentPane().add(Icon);
        Icon.setBounds(10, 70, 340, 300);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 760, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
    System.exit(0);
    }//GEN-LAST:event_exitMouseReleased

    private void disposeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseReleased
      this.setExtendedState(GameJFrame.ICONIFIED);
                                          
    }//GEN-LAST:event_disposeMouseReleased

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
     int x=evt.getXOnScreen();
     int y=evt.getYOnScreen();
    this.setLocation(x-xMouse, y-yMouse);  
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
    xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
     
        ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/ExitSimple.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
     ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/exitnt.png"));
        exit.setIcon(exitIcon);
    }//GEN-LAST:event_exitMouseEntered

    private void disposeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseEntered
    ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultIN.png"));
       dispose.setIcon(exitIcon);
    }//GEN-LAST:event_disposeMouseEntered

    private void disposeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disposeMouseExited
         ImageIcon exitIcon = new ImageIcon (getClass().getResource("/Images/defaultsimple.png"));
       dispose.setIcon(exitIcon);
    }//GEN-LAST:event_disposeMouseExited

    private void jouerButonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseEntered
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/rejouerEntred.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseEntered

    private void jouerButonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseExited
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/rejouerLeaved.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMouseExited

    private void jouerButonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMousePressed
        ImageIcon II = new ImageIcon (getClass().getResource("/Images/rejouerCliked.png"));
        jouerButon.setIcon(II);
    }//GEN-LAST:event_jouerButonMousePressed

    private void jouerButonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jouerButonMouseReleased
        this.dispose();
        new GameJFrame ().setVisible (true);
    }//GEN-LAST:event_jouerButonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel BarBackground;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Icon1;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel dispose;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jouerButon;
    private javax.swing.JLabel m;
    private javax.swing.JLabel move;
    private javax.swing.JLabel nbr;
    private javax.swing.JLabel u;
    // End of variables declaration//GEN-END:variables
}
